name: Pull Request on GitHub
on: [pull_request]
jobs:
  Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      uses: actions/checkout@v3
      - name: Make a new envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 5000
        envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/passwords"
        envkey_POSTGRES_USERNAME: "postgres"
        envkey_POSTGRES_PASSWORD: "postgres"
        envkey_POSTGRES_DB: "passwords"
        directory: back-end 
        file_name: .env.test
        fail_on_empty: true
      -name: Run tests back-end
        run: docker compose -f docker-compose-test.yml run node npm run test